# GitLab CI configuration file
# see documentation on https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - build
  - test

build:
    stage: build
    image: dockette/ci-php5:latest
    tags: 
      - php56
    script:
        - composer install
    artifacts:
        expire_in: 1 day
        paths:
        - vendor/

test:php56:
    stage: test
    image: dockette/ci-php5:latest
    tags: 
      - php56
    script:
        - composer qa
        - composer phpstan

test:php70:
    stage: test
    image: dockette/ci-php7:latest
    tags: 
      - php70
    script:
        - composer qa
        - composer phpstan
